# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MerchantiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MerchantiOS

pod 'ButtonMerchant', '~> 1'
pod 'Alamofire', '~> 4.7'

  target 'MerchantiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MerchantiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
